### ISSUE TITLE
  `expand_path': no implicit conversion of nil into String (TypeError)

### ISSUE THREAD

**Issue by deogracia** [Ultragreen/rack-auth-ldap#1]
Hi,

I'm not sure if it's a real issue or if I use it the wrong.

I want to use LDAP authentication with geminabox.

Here's 
- my Gemfile

```
# A sample Gemfile
source "https://rubygems.org"

# gem "rails"
gem "geminabox", "~> 0.12"
gem "rack-auth-ldap", "~> 1.0"
```
- my config.ru

```
require "rubygems"
require "geminabox"
require 'rack'
gem 'rack-auth-ldap'
require 'rack/auth/ldap'

Geminabox.data = "/vagrant/geminabox/geminabox-data" # ... or wherever

use Rack::Auth::Ldap

run Geminabox::Server
```
- my ./ldap.yml

```
production: &ldap_defaults
  hostname: localhost
  basedn: BASEDN
  rootdn: ROOTDN 
  passdn: XXXX
  auth: true
  port: 389
  username_ldap_attribut: uid


test:
  <<: *ldap_defaults

development:
  <<: *ldap_defaults
```

When I start with rackup, here's what I got

```
/home/vagrant/.rvm/gems/ruby-2.1.3@geminabox/gems/rack-auth-ldap-1.0/lib/rack/auth/ldap.rb:26:in `expand_path': no implicit conversion of nil into String (TypeError)
    from /home/vagrant/.rvm/gems/ruby-2.1.3@geminabox/gems/rack-auth-ldap-1.0/lib/rack/auth/ldap.rb:26:in `initialize'
    from /home/vagrant/.rvm/gems/ruby-2.1.3@geminabox/gems/rack-auth-ldap-1.0/lib/rack/auth/ldap.rb:82:in `new'
    from /home/vagrant/.rvm/gems/ruby-2.1.3@geminabox/gems/rack-auth-ldap-1.0/lib/rack/auth/ldap.rb:82:in `initialize'
    from /home/vagrant/.rvm/gems/ruby-2.1.3@geminabox/gems/rack-1.5.2/lib/rack/builder.rb:86:in `new'
    from /home/vagrant/.rvm/gems/ruby-2.1.3@geminabox/gems/rack-1.5.2/lib/rack/builder.rb:86:in `block in use'
    from /home/vagrant/.rvm/gems/ruby-2.1.3@geminabox/gems/rack-1.5.2/lib/rack/builder.rb:134:in `[]'
    from /home/vagrant/.rvm/gems/ruby-2.1.3@geminabox/gems/rack-1.5.2/lib/rack/builder.rb:134:in `block in to_app'
    from /home/vagrant/.rvm/gems/ruby-2.1.3@geminabox/gems/rack-1.5.2/lib/rack/builder.rb:134:in `each'
    from /home/vagrant/.rvm/gems/ruby-2.1.3@geminabox/gems/rack-1.5.2/lib/rack/builder.rb:134:in `inject'
    from /home/vagrant/.rvm/gems/ruby-2.1.3@geminabox/gems/rack-1.5.2/lib/rack/builder.rb:134:in `to_app'
    from /vagrant/geminabox/config.ru:13:in `<main>'
    from /home/vagrant/.rvm/gems/ruby-2.1.3@geminabox/gems/rack-1.5.2/lib/rack/builder.rb:49:in `eval'
    from /home/vagrant/.rvm/gems/ruby-2.1.3@geminabox/gems/rack-1.5.2/lib/rack/builder.rb:49:in `new_from_string'
    from /home/vagrant/.rvm/gems/ruby-2.1.3@geminabox/gems/rack-1.5.2/lib/rack/builder.rb:40:in `parse_file'
    from /home/vagrant/.rvm/gems/ruby-2.1.3@geminabox/gems/rack-1.5.2/lib/rack/server.rb:277:in `build_app_and_options_from_config'
    from /home/vagrant/.rvm/gems/ruby-2.1.3@geminabox/gems/rack-1.5.2/lib/rack/server.rb:199:in `app'
    from /home/vagrant/.rvm/gems/ruby-2.1.3@geminabox/gems/rack-1.5.2/lib/rack/server.rb:314:in `wrapped_app'
    from /home/vagrant/.rvm/gems/ruby-2.1.3@geminabox/gems/rack-1.5.2/lib/rack/server.rb:250:in `start'
    from /home/vagrant/.rvm/gems/ruby-2.1.3@geminabox/gems/rack-1.5.2/lib/rack/server.rb:141:in `start'
    from /home/vagrant/.rvm/gems/ruby-2.1.3@geminabox/gems/rack-1.5.2/bin/rackup:4:in `<top (required)>'
    from /home/vagrant/.rvm/gems/ruby-2.1.3@geminabox/bin/rackup:23:in `load'
    from /home/vagrant/.rvm/gems/ruby-2.1.3@geminabox/bin/rackup:23:in `<main>'
    from /home/vagrant/.rvm/gems/ruby-2.1.3@geminabox/bin/ruby_executable_hooks:15:in `eval'
    from /home/vagrant/.rvm/gems/ruby-2.1.3@geminabox/bin/ruby_executable_hooks:15:in `<main>'

```

The only way I found to correct it:

```
--- a/lib/rack/auth/ldap.rb
+++ b/lib/rack/auth/ldap.rb
@@ -22,6 +22,7 @@ module Rack
       # @return [Config] object himself 
       def initialize(options = { :file => './ldap.yml'})
         @values = defaults
+        options = { :file => './ldap.yml'} if options.empty?
         target  = (ENV['RACK_ENV'])? ENV['RACK_ENV'] : 'test'
         config_values = ::YAML.load_file(::File.expand_path(options[:file], Dir.pwd))[target]          
         debug = ::File.open("/tmp/test.txt",'a+')
-- 
```

Am I right or wrong ?

Thanks ^^

**Comment by ryandrake08** [comment]
I managed to fix it with:

```
options.merge!(:file => './ldap.yml') { |key,oldval,newval| oldval }
```

...which will also work if options is not empty (yet does not contain :file). See ff9f6de3ca09486635fd7678f6c0059eb1e70d2d

**Comment by agargiulo** [comment]
I also ran into this, is there a way to fix it that doesn't involve modifying the gem installed to my system?
